language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - os: osx
# Change this to your needs
script: ./autogen.sh && ./configure --enable-gtk-doc && make -j4 && make check -j4 && make distcheck 
before_install:
  - echo $TRAVIS_OS_NAME
  - ./.travis.sh
